SMT.handoutList = {
    /**
     * Each handout gets the author-name and the handout name. Example:
     * IMPORTANT: Do not forget the trailing comma!
     */
    // name: "filename.pdf",
    losada: "losada.pdf",
    giulio: "digiulio.pdf",
    rodgers: "rodgers.pdf",
    fankhauser: "fankhauser.pdf",
    hesselink: "hesselink.pptx",
    carone: "carone.pdf",
    klorman: "klorman.pdf",
    willis: "willis.pdf",
    benedict: "benedict.pdf",
    long: "long.pdf",
    hatten: "hatten.pdf",
    bonds: "bonds.pdf",
    zhang: "zhang.pdf",
    selinksky: "selinsky.pdf",
    hunt: "hunt.pdf",
    derrico: "derrico.pdf",
    vandemoortele: "vandemoortele.pdf",
    chenette: "chenette.pdf",
    manabe: "manabe.docx",
    bonds: "bonds.pdf",
    attas: "attas.pdf",
    aboyle: "aboyle.pdf",
    degraf: "degraf.pdf",
    osborn: "osborn.pdf",
    jemian: "jemian.pdf",
    thompson: "thompson.pdf",
    horlacher: "horlacher.pdf",
    gawboy: "gawboy.pdf",
    rusch: "rusch.pdf",
    johnson: "johnson.pdf",
    tymoczko: "tymoczko.pdf",
    hilewicz: "hilewicz.pdf",
    sutcliffe: "sutcliffe.pdf",
    beavers: "beavers.pdf",
    neal: "neal.pptx",
    roder: "roeder.pdf",
    woo: "woo.pptx",
    taycher: "taycher.pdf",
    watts: "watts.pdf",
    holmhudson: "holmhudson.pdf",
    jenkins: "jenkins.pptx",
    beaudoin: "beaudoin.pdf",
    rosenholtzwitt: "rosenholtz-witt.pdf",
    straus: "straus.pdf",
    rifkin: "rifkin.pdf",
    mckinney: "mckinney.pdf",
    alegant: "alegant.pdf",
    stevens: "stevens.pptx",
    bakker: "bakker.pdf",
    desimone: "desimone.pdf",
    malawey: "malawey.pptx",
    pau: "pau.pdf",
    neidich: "neidich.pdf",
    campbell: "campbell.pdf",
    goldberg: "goldberg.pdf",
    jackson: "jackson.pdf",
    benedictis: "benedictis.pdf",
    bain: "bain.pptx",
    blake: "blake.pdf",
    peres: "peres.pptx",
    vanderbeek: "vanderbeek.pdf",
    frymoyer: "frymoyer.pdf",
    mckay: "mckay.pdf",
    mak: "mak.pptx",
    hunter: "hunter.pdf",
    hermann: "hermann.pdf",
    lehman: "lehman.pdf",
    bakulina: "bakulina.docx",
    covach: "covach.pdf",
    everett: "everett.pdf",
    dobbs: "dobbs.pdf",
    gosden: "gosden.pdf",

};
