SMT.handoutList = {
    ayers: "ayers.pdf",
    cubero: "cubero.pdf",
    duncan: "duncan.pdf",
    emmery: "emmery.pdf",
    fmig: "FMIG.pdf",
    heetderks: "heetderks.pdf",
    hunt: "hunt.pdf",
    inman: "inman.pdf",
    klorman: "klorman.pdf",
    lee: "lee.pdf",
    michaelsen: "michaelsen.pdf",
    mirka: "mirka.pdf",
    nobile: "nobile.pdf",
    rabinovitch: "rabinovitch.pdf",
    ricci: "ricci.pdf",
    schachterJazz: "schachter_jazz.pdf",
    schachter: "schachter.pdf",
    schumann: "schumann.pdf",
    sofer: "sofer.pdf",
    wells: "wells.pdf",
    wfig: "work_fam_ig.pdf"
};
