title: "Music, Disability, and the Environment: Bridging Scholarship with Activism"
slug: music-disability-environment
society: AMS/SMT
layout: session
time: 'Thursday Evening, 8:00–11:00'
room: Texas F
chair:
    formatted: Jacob Cohen (Macaulay Honors College, CUNY), Anabel Maler (Indiana University), Jessica A. Holmes (University of California, Los Angeles), Chairs
    formatted_short: Jacob Cohen, Anabel Maler, and Jessica A. Holmes, Chairs
papers: ~
panelists:
    - name: Chantal Lemire
      institution: Western University
    - name: Jessica Schwartz
      institution: University of California, Los Angeles
    - name: Ailsa Lipscombe
      institution: University of Chicago
    - name: William Robin
      institution: University of Maryland
    - name: James Deaville
      institution: Carleton University
    - name: Rachel Mundy
      institution: Rutgers University-Newark
sponsor: AMS Music and Disability Study Group, SMT Music and Disability Interest Group, and AMS Ecocriticism Study Group
