---
sessiontype: 
title: "Perspectives of Black Composers"
slug: perspectives-of-black-composers
room: 
time: Saturday 12:45-2:15 ET
link: /sessions/nov6/midday/perspectives-of-black-composers
slack: 
zoom: 
chair:
    name: Panayotis Mavromatis
    institution: New York University
respondent:
    name:  
    institution: 
    formatted: Quintina Carter-Ényì (University of Georgia), Presenter
panelists: 
    - name: Jean Kidula
      institution: University of Georgia
    - name: Onyee N. Nwankpa
      institution: University of Port Harcourt, Nigeria
    - name: Gilad Rabinovitch
      institution: Florida State University
    - name: Robert Tanner
      institution: Morehouse College

