title: Producing Virtual Spaces 
slug: producing-virtual-spaces
room: Harrison
time: 'Thursday evening, 8:00–9:30'
chair:
    name: Victoria Malawey 
    institution: Macalester College
papers:
    - burke
    - douthitt
    - zinser
