# Site settings
title: "SMT 2019 - Columbus"
email: webmaster@societymusictheory.org
description: A mobile guide to our annual conference.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "guide.societymusictheory.org" # the base hostname & protocol for your site
encoding: utf-8
twitter_username: SMT_musictheory
collections:
  sessions:
    output: true

# Build settings
markdown: kramdown
