# Site settings
title: "SMT 2020 - Virtual Conference"
email: webmaster@societymusictheory.org
description: Annual conference
baseurl: "" # the subpath of your site, e.g. /blog/
url: "guide.societymusictheory.org" # the base hostname & protocol for your site
encoding: utf-8
twitter_username: SMT_musictheory

# keep junk off the web
exclude:
    - Gemfile
    - Gemfile.lock
    - CNAME
    - README.md

# Build settings
markdown: kramdown
