# Site settings
title: SMT 2015 - St. Louis
email: webmaster@societymusictheory.org
description: Mobile conference site.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "guide.societymusictheory.org" # the base hostname & protocol for your site
twitter_username: SMT_musictheory
collections:
  sessions:
    output: true

# Build settings
markdown: kramdown
