---
authors:
- name: Kai West
  institution: University of Michigan
title: "‘I Reckon You’ve Seen a Dead Body Before’: Symbolic Violence and Musical Resistance in <i>Porgy and Bess</i>"
handout: ''
abstract: |
  <p>Abstract goes here</p>

