---
authors:
- name: Kai West
  institution: University of Michigan
title: "‘I Reckon You’ve Seen a Dead Body Before’: Symbolic Violence and Musical Resistance in <i>Porgy and Bess</i>"
handout: ''
abstract: |
  <p>Describing the exchanges between black and white characters in his
  forthcoming <i>Porgy and Bess </i>(1935), George Gershwin explained in a 1934
  press release, “I am trying to get a sensational dramatic effect. I hope to
  accomplish this by having the few whites in the production speak their lines,
  while the Negroes, in answering, will sing.” Indeed, Gershwin structures the
  three scenes involving white actors so that they deliver their dialogue in
  unaccompanied speech while the black singers respond in orchestrally supported
  recitative: a dramaturgical accenting of racial difference. Furthermore, the
  libretto juxtaposes the black characters’ language, a distorted amalgam of
  African American Vernacular English and Gullah dialect, with the General
  English of the whites. These complex encounters between black and white voices
  are vital to understanding the opera, yet they remain underexplored. </p>
  <p>This paper holds a critical lens to these exchanges, investigating racial
  representation in the interplay between words and music. Beginning with
  evidence found in correspondence and newspapers, I trace the genesis and
  motive of Gershwin’s decision to create this effect. I then analyze the three
  scenes, drawing on critical race theory, Marcyliena Morgan’s work on African
  American Language Cultures, and Pierre Bourdieu’s concept of “symbolic
  violence.” By scrutinizing the power dynamics embedded in voiced expression
  and excavating layers of symbolic violence, I examine how these scenes
  emphasize racial discrimination and class divisions. </p>
  <p>Gershwin’s score, however, reveals another symbolic layer that contests the
  social hierarchies coded in the text. The Catfish Row community’s musical
  utterances oppose the spoken voices of the white outsiders who disrupt it,
  particularly in Act III, when a trio of women confound the probing questions
  of the detective. Specific harmonic and motivic structures in these
  recitatives signify the black characters’ resistance to white institutional
  authority. Thus, the opera stages its own internal tensions of race and class,
  reflecting the US’s turbulent past and resonating with a deeply unsettled
  present. Situating <i>Porgy and Bess </i>at the intersection of American opera
  and critical race studies, my research interrogates this canonical, yet
  contentious work and asks how such endeavors could support musicology’s
  participation in social justice. </p>

